[build]
  base = "/"
  command = "cd myapp && flutter build web --web-renderer html --base-href /"
  publish = "myapp/build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
