[build]
  publish = "myapp/build/web"
  command = """
    wget -qO flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.19.3-stable.tar.xz &&
    tar -xf flutter.tar.xz &&
    export PATH="$PATH:$(pwd)/flutter/bin" &&
    cd myapp &&
    ../flutter/bin/flutter config --no-analytics &&
    ../flutter/bin/flutter doctor &&
    ../flutter/bin/flutter clean &&
    ../flutter/bin/flutter pub get &&
    ../flutter/bin/flutter build web --release --web-renderer html --base-href /
  """

[build.environment]
  NODE_VERSION = "18"
  FLUTTER_VERSION = "3.19.3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
