[build]
  base = "/"
  command = """
    pwd &&
    ls -la &&
    git clone -b stable https://github.com/flutter/flutter.git &&
    export PATH="$PATH:`pwd`/flutter/bin" &&
    flutter config --no-analytics &&
    flutter pub get &&
    flutter build web --release --web-renderer html --base-href /
  """
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
