[build]
  base = "/"
  command = """
    git clone -b stable https://github.com/flutter/flutter.git &&
    export PATH="$PATH:$PWD/flutter/bin" &&
    flutter precache &&
    flutter pub get &&
    flutter build web --no-tree-shake-icons --web-renderer html --base-href /
  """
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
