[build]
  base = "myapp"    # เพิ่มบรรทัดนี้
  command = "flutter build web"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# ตั้งค่า headers สำหรับ SPA
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"
