[build]
  base = "/"
  command = """
    git clone -b stable https://github.com/flutter/flutter.git &&
    ls -la &&
    ./flutter/bin/flutter --version &&
    ./flutter/bin/flutter config --no-analytics &&
    ./flutter/bin/flutter doctor &&
    cd myapp &&
    ../flutter/bin/flutter pub get &&
    ../flutter/bin/flutter build web --release --web-renderer html --base-href /
  """
  publish = "myapp/build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
