name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  camera: ^0.11.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.2  # ใช้จัดการ path ไฟล์ฐานข้อมูล
  flutter_lints: ^5.0.0
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+4
  path: ^1.8.0
  sqlite3: ^1.3.0
  sqlite3_flutter_libs: ^0.5.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  fonts:
    - family: Questrial
      fonts:
        - asset: assets/Questrial-Regular.ttf


  assets:
    - assets/logo.png
    - assets/leaf1.jpg
    - assets/leaf2.jpg
    - assets/start2.jpg
    - assets/start.jpg
    - assets/logo3.png
